#!/bin/bash
# Demo script to show bossman capabilities

echo "Bossman - Terminal Multiplexer Demo"
echo "===================================="
echo ""
echo "Bossman allows running multiple TUI applications simultaneously"
echo "with tab-based switching between them."
echo ""
echo "Architecture:"
echo "  - Each session runs in its own PTY (pseudo-terminal)"
echo "  - Multiple sessions can run concurrently"
echo "  - Tab-based interface for easy switching"
echo "  - Real-time output capture from all sessions"
echo ""
echo "Default Sessions:"
echo "  1. Watch Date - Live date updates"
echo "  2. System Monitor - top command output"
echo "  3. Log Viewer - Simulated log stream"
echo "  4. Shell - Interactive bash shell"
echo ""
echo "Controls:"
echo "  Tab/Shift+Tab - Switch between tabs"
echo "  Ctrl+Arrow Keys - Navigate tabs"
echo "  Ctrl+1-9 - Jump to specific tab"
echo "  Ctrl+Q/C - Quit"
echo ""
echo "To run: cargo run --release"
echo ""
echo "This approach solves the nested TUI problem by:"
echo "  - Using real PTYs instead of trying to embed TUIs"
echo "  - Providing a simple tab interface"
echo "  - Supporting any TUI application (OpenCode, vim, etc.)"
